version: '3.8'

services:
  app:
    build: .
    container_name: hospital_app
    restart: always
    ports:
      - "80:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hms_db
      DB_USERNAME: hms_user
      DB_PASSWORD: hms_password
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:8.0.44-debian
    container_name: hospital_db
    restart: always
    environment:
      MYSQL_DATABASE: hms_db
      MYSQL_USER: hms_user
      MYSQL_PASSWORD: hms_password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata: