version: "3"
networks:
  application:
    driver: bridge

services:
  # --- NGINX Service Added Here ---
  nginx:
    image: nginx:alpine
    container_name: mynginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - application

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybackend
    expose:        
      - 8000
    depends_on:
      - mypgdb
    env_file:
      - .env
    networks:
      - application
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        composer install
        npm i && npm run build
        php artisan migrate
        php artisan serve --host=0.0.0.0 --port=8000
  
  mypgdb:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test-db
    networks:
      - application
    container_name: mypgdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5